baseURL = 'https://docs.hugespaceship.io/'
languageCode = 'en-us'
title = 'HugeSpaceship Docs'
[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
[params]
  themeVariant = 'hugespaceship'
